---
# Required collections definition.
#
# List of collections that should be installed before running playbooks.
# The list of collections can be installed with command:
#
# $ ansible-galaxy collection install -r requirements.yml
#
# This requires internet connectivity!

collections:
  - name: community.general
  - name: ansible.posix
  - name: containers.podman
  - name: pulp.squeezer
