---
# Playbook to destroy the demo Pulp software repository
#
# Use destroy and cleanup the "Pulp in One Container" container and Pulp pod.
#
# Dependencies:
#   collections:
#     - container.podman
#

- name: Nuke the Pulp in One Container pod and data
  hosts: localhost
  connection: local
  vars:
    # Name of container to destroy
    pulp_container_name: pulp
    pulp_pod_name: pulppod
    # Path where the container volume mounts have been made
    pulp_storage_directory: "{{ ansible_user_dir }}/Projects/pulp"

  tasks:
    - name: Stop the Pulp pod
      ansible.builtin.systemd_service:
        name: "{{ pulp_pod_name }}-pod.service"
        state: stopped
        enabled: false
        scope: user

    - name: Remove the Podman Quadlet files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ ansible_facts.user_dir }}/.config/containers/systemd/{{ pulp_container_name }}.container"
        - "{{ ansible_facts.user_dir }}/.config/containers/systemd/{{ pulp_pod_name }}.pod"
      notify:
        - Perform systemd daemon-reload

    - name: Wipe directories that preserve Pulp state
      become: true
      become_method: containers.podman.podman_unshare
      ansible.builtin.file:
        path: "{{ pulp_storage_directory }}"
        state: absent

  handlers:
    - name: Perform systemd daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true
        scope: user
